server:
  port: 8080

captcha:
  length: 3
  symbols: "abcdefghijklmnopqrstuvwxyz1234567890"

database:
  url: http://localhost:8050

reg:
  person:
    isApproved: true
    isBlocked: false
    messagePermission: ALL