server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/team43
    username: skillbox43
    password: skillbox43
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

captcha:
  length: 3
  symbols: "abcdefghijklmnopqrstuvwxyz1234567890"

database:
  url: http://localhost:8050

reg:
  person:
    isApproved: true
    isBlocked: false
    messagePermission: ALL

app:
  security:
    passwordStrength: 12