server:
  port: 8050

spring:

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  liquibase:
    change-log: src/main/resources/db/changelog/master.xml
    changeLogFile: src/main/resources/db/changelog/master.xml
    enabled: false

cloudinary:
  parameters:
    cloud_name: ddrbvclx4
    api_key: 885654915398544
    api_secret: yNc-utCrfPNjDFDXiN2X75ZcSfg
    secure: true
