INSERT INTO notification_setting (id,
                    enable_like,
                    enable_post,
                    enable_post_comment,
                    enable_comment_comment,
                    enable_message,
                    enable_friend_request,
                    enable_friend_birthday,
                    enable_send_email_message)
VALUES
        ('1000',
        FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('1001',
         FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('1002',
         FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('1003',
         FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('1004',
         FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('1005',
         FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('1006',
         FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('1007',
         FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('1008',
         FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('1009',
         FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE)
