version: '3.7'

services:
  gateway:
    image: skillbox43/social-net-backend:gateway
    container_name: "gateway"
    networks:
      - social-net
    ports:
      - "8030:8030"

  communication:
    image: skillbox43/social-net-backend:communication
    container_name: "communication"
    networks:
      - social-net
    ports:
      - "8081:8081"

  database:
    image: skillbox43/social-net-backend:database
    container_name: "database"
    networks:
      - social-net
    ports:
      - "8050:8050"

  friendship:
    image: skillbox43/social-net-backend:friendship
    container_name: "friendship"
    networks:
      - social-net
    ports:
      - "8082:8082"

  profile:
    image: skillbox43/social-net-backend:profile
    container_name: "profile"
    networks:
      - social-net
    ports:
      - "8080:8080"

  grafana:
    build: './config/grafana'
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - social-net

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      - social-net

networks:
  social-net:
    driver: bridge