server:
  port: 8030

app:
  jwt:
    accessSecret: "lPe3yPuSbhxNZDu69agqpG0K8dYvFI5nFQBnb5C+uAENVWBT0LpZ0Qw5cUqPIturca4v4FpgDoVUt/O5l0IwEQ=="
    refreshSecret: "rtf5wCZIcY3BNYSNlsJx3rq00fTQUPfzGgnBan2RgNKRn6UNi1eb6ooMX4q2qi++95mtjs3M4wGaP44thuI8CA=="
    accessTokenLifeTime: 3m
    refreshTokenLifeTime: 30m
    authScheme: Bearer
  security:
    passwordStrength: 12
  frontend: http://localhost:8099

database:
  url: http://localhost:8050

profile:
  url: http://localhost:8080