server:
  port: 8030

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

max-image-size: 1048576

app:
  jwt:
    accessTokenLifeTime: 20m
    refreshTokenLifeTime: 2h
    authScheme: Bearer
  security:
    passwordStrength: 12
  frontend: http://localhost:8099

database:
  url: http://localhost:8050

profile:
  url: http://localhost:8080